apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: longhorn-storage
volumeBindingMode: WaitForFirstConsumer
provisioner: driver.longhorn.io
parameters:
  numberOfReplicas: '1'
  staleReplicaTimeout: '30'