apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
      name: pidtoo-iris-application
      namespace: argocd
spec:
      destination:
        namespace: isc
        server: https://kubernetes.default.svc
      project: default
      source:
        path: iko/iris_operator_amd-3.8.42.100/samples
        repoURL: {{ .Values.repoURL }}
        targetRevision: {{ .Values.targetRevision }}
      containers:
      - name: iris
        ##image: containers.intersystems.com/intersystems/iris-community:2024.3
        env:
        - name: ISC_DATA_DIRECTORY
          value: /storage/iris
        volumeMounts:
        - name: iris-sys-storage
        mountPath: /storage/iris
      volumeMounts:
      - name: iris-sys-storage
      persistentVolumeClaim:
        claimName: iris-pvc
      syncPolicy:
        automated: {}
        syncOptions:
        - CreateNamespace=true